# -*- coding: utf-8 -*-
"""genai_translate.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14Y74LVi0kdT-nZ0a9jx36YPrACp9iNQa
"""

!pip install langchain-google-genai
import os
from langchain.chat_models import init_chat_model

os.environ['GOOGLE_API_KEY'] = 'your api key'

model = init_chat_model('google_genai:gemini-2.5-flash-lite')

responce = model.invoke('about software jobs in 2026 and 2030?')

from langchain_core.messages import HumanMessage,SystemMessage

messages = [
    SystemMessage('translate the following from english to odia language'),
    HumanMessage('what is the capital of india')
]

model.invoke(messages)

from langchain_core.messages import HumanMessage,SystemMessage

messages = [
    SystemMessage('translate the following from english to odia language'),
    HumanMessage('हिंदी शब्द के अर्थ जानने के लिए हिंदी डिक्शनरी में अपना शब्द टाइप कीजिए। इस शब्दकोश के ज़रिए जुड़िए और सुझाव दीजिए हिंदी क्षेत्र की भाषाओं-बोलियों के व्यापक शब्दकोश को')
]

model.invoke(messages)